# Generated by Django 5.2.6 on 2025-09-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default='pending', max_length=50, verbose_name='Nombre'),
        ),
    ]
